### ISSUE TITLE
Automate the extension release process

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/browser-extension#247]
### Problem
Currently our browser extension release process doesn't use the CI/CD Jenkins setup. Releasing the browser extension is therefore a more manual process, which can mean that not all team members can release the extension, or feel comfortable releasing the extension. 

### What's Needed
After talking with @robertknight, we agreed that we should move the extension release process into the current CI/CD process that we're already using for other apps. This will help automate the process so that everyone can release the extension as needed. 

### Sub-tasks

- [x] Add Jenkins project to build, test and deploy the browser extension (https://github.com/hypothesis/browser-extension/pull/300, https://github.com/hypothesis/browser-extension/pull/301)
- [x] Add method to create a new browser extension version with the latest Hypothesis client (https://github.com/hypothesis/browser-extension/pull/307, [Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1582624801011700))
- [x] Trigger an update of the QA browser extension when a new Hypothesis client version is released to production. Production releases of the browser extension will still require manual intervention (https://github.com/hypothesis/client/pull/1877)
- [x] Update [documentation in playbook repository](https://github.com/hypothesis/playbook/blob/master/docs/chrome-extension.md), SO4T to reflect extension release process changes (https://github.com/hypothesis/playbook/pull/270)
- [x] Figure out why the process of uploading, signing and then downloading the Firefox extension using `web-ext` is taking such a long time (see [comment](https://github.com/hypothesis/browser-extension/issues/247#issuecomment-596398632))
- [x] Make a decision about whether to keep or remove the Travis build for the time being (nb. The main affordance Travis provides is that it is accessible to non-Hypothesis developers, whereas Jenkins is not) (@robertknight - I'm proposing to keep this for now. We can always revisit later. See https://github.com/hypothesis/browser-extension/pull/311)

### Follow-up work

(Check items when either done or filed as an issue and scheduled for future)

- [x] Rename the "stage" extension to "QA" everywhere in the browser-extension repo, as it is confusing that we use the term "QA" for all other projects but "stage" for the browser extension pre-prod release in some places (https://github.com/hypothesis/browser-extension/pull/309)
- [x] Make it easier to update the QA extension after a new release (@robertknight - this is currently a PITA that requires me to log into the Chrome Web Store, remove and re-add the extension) (_Update: A solution for this is to create a new Chrome profile which is connected to your Hypothesis Google account. This will enable Chrome's extension auto-update to work for the Hypothesis QA extension_ - @robertknight)
- [x] Filter out progress logs from `web-ext sign` (it currently prints many "frames" of a progress. bar as if the Jenkins output log was an interactive terminal) (https://github.com/hypothesis/browser-extension/pull/317)
- [x] Optimize the process of uploading+signing+download the Firefox extension (see [comment](https://github.com/hypothesis/browser-extension/issues/247#issuecomment-596398632) for ideas) (https://github.com/hypothesis/browser-extension/pull/317)
- [ ] Make it possible to publish the prod extension directly from Jenkins
- [ ] Remove need for Chrome extension to request broad permissions upon installation as this makes compliance reviews of new updates more likely which in turn affects our ability to ship new releases promptly

**Comment by robertknight** [comment]
Regarding the slow deployment due to this issue with web-ext:

> Figure out why the process of uploading, signing and then downloading the Firefox extension using web-ext is taking such a long time

The issue here, as I currently understand it, is that the deployment script runs `web-ext sign` which:

1. Uploads the extension into a queue for validation and signing
2. Waits for the automated validation and signing steps to complete
3. Downloads the result

Step (2) can take a long time. In contrast the Chrome extension deployment uploads the extension but AFAIK doesn't wait for automated checks to complete before it returns. This is generally not a problem since, when the upload does complete, the extension will be available from the Chrome Web Store.

In the case of Firefox, we're planning to host the extension ourselves, so we need to wait until it is successfully signed, download it and then upload it to wherever it is going to be hosted. Right now we're not actually shipping the Firefox extension, but I've tried to keep the build working so at least we're not moving further away from having it working.

One potentially easy thing we can do is to upload+sign the QA and prod Firefox extensions concurrently rather than one after the other.

**Comment by robertknight** [comment]
We've done the essential parts of this. The two remaining items for a) making it possible to publish to prod directly from Jenkins and b) reducing the permissions required by the Chrome extension are left as exercises for the future.
